### ISSUE TITLE
get request returned only small portion of the body text

### ISSUE THREAD

**Issue by strobe** [amrhassan/scala-httpc#17] opened 2016-10-09 14:27 UTC
for example 
```
scala> val r = run(get("https://news.ycombinator.com")).right.get.text
r: Option[String] =
Some(3dfc
<html op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?0jKc9Keyn2Zl7D1UAQcy">
        <link rel="shortcut icon" href="favicon.ico">
          <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
        <title>Hacker News</title>
      </head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="http://www.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white so...
scala> run(get("https://techcrunch.com")).right.get.text.get.length()
res7: Int = 848
```

may be it related to #13

**Comment by amrhassan** [comment] 2016-10-09 18:33
I think this is because of #18. I'll see if I can work out a solution.

**Comment by amrhassan** [comment] 2016-10-09 21:25
Oh wait, it's probably caused by #19. Gotta implement support for that.

**Comment by amrhassan** [comment] 2016-10-10 19:41
I think this is fixed now. Please reopen if otherwise.

**Closed by amrhassan** 2016-10-10 19:41 UTC
